name: publish

on:
  push:
    branches: [main, postprint]
    paths-ignore:
      - 'README.md'

jobs:
  build-and-execute:
    uses: eds-book/notebooks-workflows/.github/workflows/build.yaml@main
    secrets:
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
      NASA_EARTHDATA_USER: ${{ secrets.NASA_EARTHDATA_USER }}
      NASA_EARTHDATA_PWD: ${{ secrets.NASA_EARTHDATA_PWD }}

  deploy:
    needs: build-and-execute
    uses: eds-book/notebooks-workflows/.github/workflows/deploy.yaml@main